/**
 * SysCtrl Theme Engine
 * Each theme exposes: colors, fonts, animations, sounds, icons, wallpaper
 */

export const THEMES = {

  // ── Default: Neon Cyber (your original style, refined) ──────────────────
  cyber: {
    id: "cyber",
    name: "Cyber",
    accent:      "#00E5FF",
    accentSoft:  "#00B8D4",
    bg:          "#000000",
    surface:     "#080808",
    card:        "#0D0D0D",
    border:      "#1A1A1A",
    text:        "#FFFFFF",
    textMuted:   "#555555",
    textDim:     "#2A2A2A",
    danger:      "#FF3B30",
    warning:     "#FF9F0A",
    success:     "#30FF80",
    gaugeColors: ["#00E5FF", "#2979FF"],
    batteryColors: { low: "#FF3B30", mid: "#FF9F0A", high: "#00E5FF", full: "#30FF80" },
    cardStyle:   { borderRadius: 14, borderWidth: 0.5 },
    headerStyle: { borderBottomWidth: 0.5 },
    fontScale:   1.0,
    animations:  { speed: 1.0, spring: { tension: 300, friction: 30 } },
    sectionLabel: { letterSpacing: 3, textTransform: "uppercase", fontSize: 9 },
  },

  // ── Cyberpunk ────────────────────────────────────────────────────────────
  cyberpunk: {
    id: "cyberpunk",
    name: "Cyberpunk",
    accent:      "#FF00FF",
    accentSoft:  "#CC00CC",
    bg:          "#0A0010",
    surface:     "#110018",
    card:        "#160020",
    border:      "#2A0040",
    text:        "#FF00FF",
    textMuted:   "#660066",
    textDim:     "#330033",
    danger:      "#FF3300",
    warning:     "#FFAA00",
    success:     "#00FF66",
    gaugeColors: ["#FF00FF", "#00FFFF"],
    batteryColors: { low: "#FF3300", mid: "#FFAA00", high: "#FF00FF", full: "#00FFFF" },
    cardStyle:   { borderRadius: 0, borderWidth: 1 },
    headerStyle: { borderBottomWidth: 1 },
    fontScale:   1.0,
    animations:  { speed: 1.2, spring: { tension: 400, friction: 20 } },
    sectionLabel: { letterSpacing: 4, textTransform: "uppercase", fontSize: 8 },
  },

  // ── Minimal Dark ────────────────────────────────────────────────────────
  minimal: {
    id: "minimal",
    name: "Minimal Dark",
    accent:      "#FFFFFF",
    accentSoft:  "#CCCCCC",
    bg:          "#111111",
    surface:     "#181818",
    card:        "#1E1E1E",
    border:      "#2A2A2A",
    text:        "#FFFFFF",
    textMuted:   "#777777",
    textDim:     "#444444",
    danger:      "#FF453A",
    warning:     "#FFD60A",
    success:     "#32D74B",
    gaugeColors: ["#FFFFFF", "#888888"],
    batteryColors: { low: "#FF453A", mid: "#FFD60A", high: "#AAAAAA", full: "#32D74B" },
    cardStyle:   { borderRadius: 8, borderWidth: 0.5 },
    headerStyle: { borderBottomWidth: 0.5 },
    fontScale:   1.0,
    animations:  { speed: 0.8, spring: { tension: 200, friction: 40 } },
    sectionLabel: { letterSpacing: 2, textTransform: "uppercase", fontSize: 10 },
  },

  // ── Batman ──────────────────────────────────────────────────────────────
  batman: {
    id: "batman",
    name: "Batman",
    accent:      "#FFD700",
    accentSoft:  "#C8A800",
    bg:          "#050505",
    surface:     "#0A0A0A",
    card:        "#0F0F0F",
    border:      "#1A1400",
    text:        "#FFD700",
    textMuted:   "#554400",
    textDim:     "#2A2200",
    danger:      "#FF2200",
    warning:     "#FF8800",
    success:     "#44FF00",
    gaugeColors: ["#FFD700", "#FF8800"],
    batteryColors: { low: "#FF2200", mid: "#FF8800", high: "#FFD700", full: "#FFD700" },
    cardStyle:   { borderRadius: 4, borderWidth: 0.5 },
    headerStyle: { borderBottomWidth: 0.5 },
    fontScale:   1.0,
    animations:  { speed: 0.9, spring: { tension: 280, friction: 35 } },
    sectionLabel: { letterSpacing: 4, textTransform: "uppercase", fontSize: 9 },
  },

  // ── RGB Gamer ────────────────────────────────────────────────────────────
  gamer: {
    id: "gamer",
    name: "RGB Gamer",
    accent:      "#00FF41",
    accentSoft:  "#00CC33",
    bg:          "#000A00",
    surface:     "#000F00",
    card:        "#001500",
    border:      "#003300",
    text:        "#00FF41",
    textMuted:   "#006600",
    textDim:     "#003300",
    danger:      "#FF0000",
    warning:     "#FFFF00",
    success:     "#00FF41",
    gaugeColors: ["#00FF41", "#00CCFF"],
    batteryColors: { low: "#FF0000", mid: "#FFFF00", high: "#00FF41", full: "#00FF41" },
    cardStyle:   { borderRadius: 6, borderWidth: 1 },
    headerStyle: { borderBottomWidth: 1 },
    fontScale:   1.0,
    animations:  { speed: 1.3, spring: { tension: 500, friction: 20 } },
    sectionLabel: { letterSpacing: 3, textTransform: "uppercase", fontSize: 9 },
  },

  // ── Hello Kitty ──────────────────────────────────────────────────────────
  kitty: {
    id: "kitty",
    name: "Hello Kitty",
    accent:      "#FF69B4",
    accentSoft:  "#FF1493",
    bg:          "#FFF0F5",
    surface:     "#FFE4EF",
    card:        "#FFFFFF",
    border:      "#FFB6C1",
    text:        "#C2185B",
    textMuted:   "#F48FB1",
    textDim:     "#FCE4EC",
    danger:      "#E91E63",
    warning:     "#FF6B35",
    success:     "#66BB6A",
    gaugeColors: ["#FF69B4", "#FF1493"],
    batteryColors: { low: "#E91E63", mid: "#FF6B35", high: "#FF69B4", full: "#66BB6A" },
    cardStyle:   { borderRadius: 20, borderWidth: 1 },
    headerStyle: { borderBottomWidth: 1 },
    fontScale:   1.0,
    animations:  { speed: 0.7, spring: { tension: 150, friction: 50 } },
    sectionLabel: { letterSpacing: 1, textTransform: "none", fontSize: 11 },
  },

  // ── Matrix ───────────────────────────────────────────────────────────────
  matrix: {
    id: "matrix",
    name: "Matrix",
    accent:      "#00FF41",
    accentSoft:  "#009920",
    bg:          "#000000",
    surface:     "#001100",
    card:        "#001800",
    border:      "#003300",
    text:        "#00FF41",
    textMuted:   "#007700",
    textDim:     "#003300",
    danger:      "#FF0000",
    warning:     "#AAFF00",
    success:     "#00FF41",
    gaugeColors: ["#00FF41", "#00AA00"],
    batteryColors: { low: "#FF0000", mid: "#AAFF00", high: "#00FF41", full: "#00FF41" },
    cardStyle:   { borderRadius: 0, borderWidth: 0.5 },
    headerStyle: { borderBottomWidth: 0.5 },
    fontScale:   1.0,
    animations:  { speed: 1.5, spring: { tension: 600, friction: 15 } },
    sectionLabel: { letterSpacing: 5, textTransform: "uppercase", fontSize: 8 },
  },

  // ── Retro XP ─────────────────────────────────────────────────────────────
  xp: {
    id: "xp",
    name: "Windows XP",
    accent:      "#0078D7",
    accentSoft:  "#0063B1",
    bg:          "#236BCC",
    surface:     "#1A5CB8",
    card:        "#ECE9D8",
    border:      "#919B9C",
    text:        "#003399",
    textMuted:   "#666699",
    textDim:     "#9999CC",
    danger:      "#CC0000",
    warning:     "#FF9900",
    success:     "#009900",
    gaugeColors: ["#0078D7", "#00A000"],
    batteryColors: { low: "#CC0000", mid: "#FF9900", high: "#0078D7", full: "#009900" },
    cardStyle:   { borderRadius: 4, borderWidth: 2 },
    headerStyle: { borderBottomWidth: 2 },
    fontScale:   1.0,
    animations:  { speed: 0.6, spring: { tension: 120, friction: 60 } },
    sectionLabel: { letterSpacing: 0, textTransform: "none", fontSize: 11 },
  },
};

export const DEFAULT_THEME_ID = "cyber";

export function getTheme(id) {
  return THEMES[id] || THEMES[DEFAULT_THEME_ID];
}

export const THEME_LIST = Object.values(THEMES);